[2023-10-10T06:47:28.609+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump manual__2023-10-10T06:47:25.593295+00:00 [queued]>
[2023-10-10T06:47:28.614+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump manual__2023-10-10T06:47:25.593295+00:00 [queued]>
[2023-10-10T06:47:28.614+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T06:47:28.620+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_dump> on 2023-10-10 06:47:25.593295+00:00
[2023-10-10T06:47:28.624+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2023-10-10T06:47:28.628+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mongo_data_loader', 'generate_dump', 'manual__2023-10-10T06:47:25.593295+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/mongo_data_loader.py', '--cfg-path', '/tmp/tmpcd_oo62s']
[2023-10-10T06:47:28.630+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask generate_dump
[2023-10-10T06:47:28.660+0000] {task_command.py:415} INFO - Running <TaskInstance: mongo_data_loader.generate_dump manual__2023-10-10T06:47:25.593295+00:00 [running]> on host 156ef8e9d1a9
[2023-10-10T06:47:28.703+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_data_loader' AIRFLOW_CTX_TASK_ID='generate_dump' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T06:47:25.593295+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-10T06:47:25.593295+00:00'
[2023-10-10T06:47:32.609+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mongo_data_loader.py", line 32, in generate_dump
    generate_raw_dump.generate_job_dump()
  File "/opt/airflow/dags/generate_raw_dump.py", line 64, in generate_job_dump
    job_details_dict = jobs_details(job_ids)
  File "/opt/airflow/dags/generate_raw_dump.py", line 49, in jobs_details
    counter += 1
UnboundLocalError: local variable 'counter' referenced before assignment
[2023-10-10T06:47:32.636+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=mongo_data_loader, task_id=generate_dump, execution_date=20231010T064725, start_date=20231010T064728, end_date=20231010T064732
[2023-10-10T06:47:32.654+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task generate_dump (local variable 'counter' referenced before assignment; 65)
[2023-10-10T06:47:32.687+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T06:47:32.706+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
