[2023-12-03T05:12:43.218+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump manual__2023-12-03T05:12:37.041408+00:00 [queued]>
[2023-12-03T05:12:43.254+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump manual__2023-12-03T05:12:37.041408+00:00 [queued]>
[2023-12-03T05:12:43.255+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-12-03T05:12:43.282+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_dump> on 2023-12-03 05:12:37.041408+00:00
[2023-12-03T05:12:43.309+0000] {standard_task_runner.py:57} INFO - Started process 119 to run task
[2023-12-03T05:12:43.314+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mongo_data_loader', 'generate_dump', 'manual__2023-12-03T05:12:37.041408+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/mongo_data_loader.py', '--cfg-path', '/tmp/tmpbk3zk40_']
[2023-12-03T05:12:43.329+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask generate_dump
[2023-12-03T05:12:43.424+0000] {task_command.py:415} INFO - Running <TaskInstance: mongo_data_loader.generate_dump manual__2023-12-03T05:12:37.041408+00:00 [running]> on host 0dd9b00a73f6
[2023-12-03T05:12:43.533+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_data_loader' AIRFLOW_CTX_TASK_ID='generate_dump' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T05:12:37.041408+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T05:12:37.041408+00:00'
[2023-12-03T05:13:51.973+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mongo_data_loader.py", line 32, in generate_dump
    generate_raw_dump.generate_job_dump()
  File "/opt/airflow/dags/generate_raw_dump.py", line 64, in generate_job_dump
    job_details_dict = jobs_details(job_ids)
  File "/opt/airflow/dags/generate_raw_dump.py", line 46, in jobs_details
    fetched_details = response.json()['data'][0]
KeyError: 'data'
[2023-12-03T05:13:51.987+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=mongo_data_loader, task_id=generate_dump, execution_date=20231203T051237, start_date=20231203T051243, end_date=20231203T051351
[2023-12-03T05:13:51.997+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task generate_dump ('data'; 119)
[2023-12-03T05:13:52.029+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T05:13:52.046+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
