[2023-10-10T17:17:57.353+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump scheduled__2023-09-10T16:45:00+00:00 [queued]>
[2023-10-10T17:17:57.357+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump scheduled__2023-09-10T16:45:00+00:00 [queued]>
[2023-10-10T17:17:57.357+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T17:17:57.363+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_dump> on 2023-09-10 16:45:00+00:00
[2023-10-10T17:17:57.367+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2023-10-10T17:17:57.371+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mongo_data_loader', 'generate_dump', 'scheduled__2023-09-10T16:45:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/mongo_data_loader.py', '--cfg-path', '/tmp/tmpnvmiga69']
[2023-10-10T17:17:57.374+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask generate_dump
[2023-10-10T17:17:57.406+0000] {task_command.py:415} INFO - Running <TaskInstance: mongo_data_loader.generate_dump scheduled__2023-09-10T16:45:00+00:00 [running]> on host 7c5595238a2f
[2023-10-10T17:17:57.449+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_data_loader' AIRFLOW_CTX_TASK_ID='generate_dump' AIRFLOW_CTX_EXECUTION_DATE='2023-09-10T16:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-10T16:45:00+00:00'
[2023-10-10T17:20:03.148+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-10T17:20:03.159+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=mongo_data_loader, task_id=generate_dump, execution_date=20230910T164500, start_date=20231010T171757, end_date=20231010T172003
[2023-10-10T17:20:03.176+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-10T17:20:03.190+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-03T05:12:43.957+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump scheduled__2023-09-10T16:45:00+00:00 [queued]>
[2023-12-03T05:12:43.965+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_data_loader.generate_dump scheduled__2023-09-10T16:45:00+00:00 [queued]>
[2023-12-03T05:12:43.967+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-12-03T05:12:43.977+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_dump> on 2023-09-10 16:45:00+00:00
[2023-12-03T05:12:43.983+0000] {standard_task_runner.py:57} INFO - Started process 131 to run task
[2023-12-03T05:12:43.987+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mongo_data_loader', 'generate_dump', 'scheduled__2023-09-10T16:45:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/mongo_data_loader.py', '--cfg-path', '/tmp/tmpj3oyzx03']
[2023-12-03T05:12:43.992+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask generate_dump
[2023-12-03T05:12:44.078+0000] {task_command.py:415} INFO - Running <TaskInstance: mongo_data_loader.generate_dump scheduled__2023-09-10T16:45:00+00:00 [running]> on host 0dd9b00a73f6
[2023-12-03T05:12:44.170+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_data_loader' AIRFLOW_CTX_TASK_ID='generate_dump' AIRFLOW_CTX_EXECUTION_DATE='2023-09-10T16:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-10T16:45:00+00:00'
[2023-12-03T05:13:51.928+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mongo_data_loader.py", line 32, in generate_dump
    generate_raw_dump.generate_job_dump()
  File "/opt/airflow/dags/generate_raw_dump.py", line 64, in generate_job_dump
    job_details_dict = jobs_details(job_ids)
  File "/opt/airflow/dags/generate_raw_dump.py", line 46, in jobs_details
    fetched_details = response.json()['data'][0]
KeyError: 'data'
[2023-12-03T05:13:51.938+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=mongo_data_loader, task_id=generate_dump, execution_date=20230910T164500, start_date=20231203T051243, end_date=20231203T051351
[2023-12-03T05:13:51.948+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task generate_dump ('data'; 131)
[2023-12-03T05:13:51.994+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T05:13:52.024+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
